name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - name: Check out repository
        uses: actions/checkout@v2

      # 2) Set up Java 17 using Temurin distribution
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3) Build with Maven
      - name: Build with Maven
        run: |
          mvn -B package

      # 4) Run tests (also from the subfolder)
      - name: Run tests
        run: |
          mvn test
